name: Docker Build

on:
  schedule:
  - cron: "0 6 * * *"
  
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --context aws-sg-inbound-check --tag barsilver/aws-sg-inbound-check:${GITHUB_SHA} -t barsilver/aws-sg-inbound-check:latest

    - name: Push the Docker image
      run: |
        docker push barsilver/aws-sg-inbound-check:${GITHUB_SHA}
        docker push barsilver/aws-sg-inbound-check:latest

        

      
